# Generated by Django 5.1.5 on 2025-01-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('invoice', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('chno', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('controller', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=50)),
                ('battery_no', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_details',
            },
        ),
    ]
