# Generated by Django 5.1.5 on 2025-01-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='details',
        ),
    ]
