# Generated by Django 5.1.5 on 2025-02-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_module_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='type',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
