# Generated by Django 5.1.6 on 2025-03-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_details_remark_details_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='battery_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='charge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='chno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='controller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='motor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='remark',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
